### ISSUE TITLE
Plugin not used in development build?

### ISSUE THREAD

**Issue by canonic-epicure** [jkzing/vue-cli-plugin-multi-compiler#1]
Hi,

Thanks for this plugin, it solves exactly the problem I had.

One thing though - the plugin seems to be ignored for the development builds?

In the `vue.config.js` I have: 
```js
  pluginOptions: {
    configureMultiCompilerWebpack: webpackConfig => {
      console.log('MULTI')

      process.exit()
```
Then, for production build, the plugin outputs the "MULTI" and exits the build, as expected:
```
$ npx vue-cli-service build --mode production

⠋  Building for production...MULTI
nickolay@outpost:~/workspace/Bryntum/vuestic-admin
```
But for development builds, it happily build the whole project - seems the plugin is ignored?
```
nickolay@outpost:~/workspace/Bryntum/vuestic-admin$ npx vue-cli-service build --mode dev

 65% building modules 1273/1368 modules 95 active ...uesticIcon.vue?vue&type=script&lang=js&DEPRECATION WARNING on line 1, column 8 of /home/nickolay/workspace/Bryntum/vuestic-admin/src/vuestic-theme/vuestic-sass/global/_reset.scss:
Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass.
Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

 98% after emitting CopyPlugin

 DONE  Compiled successfully in 17795ms   
```

Or am I missing something?

**Comment by jkzing** [comment]
If you read `index.j`, you will find out: 
[https://github.com/jkzing/vue-cli-plugin-multi-compiler/blob/0fcd6879e4ea7b0468801772c5be87e55b6cd034/index.js#L2](https://github.com/jkzing/vue-cli-plugin-multi-compiler/blob/0fcd6879e4ea7b0468801772c5be87e55b6cd034/index.js#L2)

Actually I had it enabled in first version, after that I found it quiet buggy in dev mode. As I don't need it in dev mode, so...

Anyways if you want to use it in dev mode, you can take the source code and have a try yourself. The code is quite simple (about 10 lines).😊

**Comment by canonic-epicure** [comment]
Ah, I see.. Thanks for explanations. Wouldn't it be more consistent to enable this plugin for dev mode too? You could just enable it conditionally in your setup, as with other plugins. Just don't want to publish my own copy of your plugin :)

**Comment by jkzing** [comment]
> Wouldn't it be more consistent to enable this plugin for dev mode too?

As I said above, it's buggy in dev mode. Which is because Vue CLI assumes `webpackConfig` is an `object` in command `serve`, see details here https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-service/lib/commands/serve.js. There is no easy way to bypass that (without change source code in `serve.js`). 

AFAIK, webpack `multi compiler` mode is usually used in "build mode" (w/o `dev-server`). If you really need it In dev mode, you can just start two processes with different configs.

**Comment by jkzing** [comment]
BTW, you can just write you own custom plugin in your project and load it via [https://cli.vuejs.org/guide/plugins-and-presets.html#project-local-plugin](https://cli.vuejs.org/guide/plugins-and-presets.html#project-local-plugin) without publish it to npm. Just FYI.

**Comment by canonic-epicure** [comment]
I see. Asked for recommendations in the original [thread](https://github.com/vuejs/vue-cli/issues/2613).
